# Generated by Django 3.0.8 on 2020-07-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashAsPie', '0002_auto_20200709_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_order',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
