# Generated by Django 3.0.8 on 2020-07-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashAsPie', '0003_auto_20200709_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
