# Generated by Django 3.0.8 on 2020-07-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashAsPie', '0005_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=123545),
            preserve_default=False,
        ),
    ]
