# Generated by Django 3.0.8 on 2020-07-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashAsPie', '0007_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2342332242, max_length=35),
            preserve_default=False,
        ),
    ]
